NFC_DEBUG_ENABLED=1

NFA_STORAGE="/data/nfc"
PRESERVE_STORAGE=0x01

SCREEN_OFF_POWER_STATE=1

NFA_DM_DISC_DURATION_POLL=500

POLLING_TECH_MASK=0x2F

P2P_LISTEN_TECH_MASK=0x00

AID_MATCHING_MODE=0x01

PARTIAL_AID={02:01:05}

UICC_LISTEN_TECH_MASK=0x07

NFA_HCI_USE_FORCE_SETTING=0x00
NFA_HCI_ESE_CHIP_TYPE=0x01
NFA_HCI_DEFAULT_STATIC_PIPE_TYPE=0x01

ESE_POWER_STABLE_TIME=50

NFA_PROPRIETARY_CFG_CLT=0x90

ACTIVE_SE=0x82

NFA_AID_BLOCK_ROUTE=1

NCI_RESET_TYPE=0x00

LEGACY_MIFARE_READER=1
